from pathlib import Path
root=Path('/mnt/data/paulcodeai-preschool-colorful')

def shell(title, desc, body, active='index.html', no_chat=False):
    chat = '' if no_chat else r'''
<button class="ai-fab open-ai" type="button" aria-label="Open Virtual Admissions Assistant"><span>✦</span> Chat with Admissions</button>
<aside class="ai-panel" aria-hidden="true" aria-label="Virtual Admissions Assistant">
  <div class="ai-head"><div><b>Little Bloom Admissions</b><small>Virtual Admissions Assistant</small></div><span class="online">● Online</span><button class="ai-close" type="button" aria-label="Close assistant">×</button></div>
  <div class="chat-system">Ask about programs, fees, activities, timings or admissions. You can type your question naturally.</div>
  <div class="ai-body" id="chat-messages"><div class="chat-row bot"><div class="avatar">LB</div><div class="bubble">Hi! I’m the Little Bloom Admissions Assistant. How can I help you today?</div></div></div>
  <div class="suggestions"><button type="button">Which program suits a 3-year-old?</button><button type="button">What are the fees?</button><button type="button">How does admission work?</button></div>
  <form class="chat-form" id="chat-form"><input id="chat-input" type="text" maxlength="500" placeholder="Ask a question…" autocomplete="off" required><button type="submit" aria-label="Send message">➤</button></form>
  <div class="ai-note">A virtual admissions assistant for quick information. Final details should be confirmed with the school.</div>
</aside>'''
    return f'''<!doctype html>
<html lang="en-IN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{desc}"><meta name="theme-color" content="#24324B"><title>{title} | Little Bloom Early Learning Centre</title><link rel="stylesheet" href="css/style.css"></head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<div class="topline"><div class="container"><span>Early learning with care, curiosity & confidence</span><span class="right">Surat, Gujarat</span></div></div>
<header class="site-header"><div class="container nav-wrap">
<a class="brand" href="index.html" aria-label="Little Bloom home"><span class="brand-mark">LB</span><span class="brand-copy"><strong>Little Bloom</strong><small>Early Learning Centre</small></span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Open menu">☰</button>
<nav id="site-nav" class="site-nav" aria-label="Primary navigation">
<a href="index.html" data-page="index.html">Home</a><a href="about.html" data-page="about.html">About</a><a href="programs.html" data-page="programs.html">Programs</a><a href="activities.html" data-page="activities.html">Activities</a><a href="gallery.html" data-page="gallery.html">Gallery</a><a href="admission.html" data-page="admission.html">Admissions</a><a href="contact.html" data-page="contact.html" class="nav-cta">Contact</a>
</nav></div></header>
<main id="main">{body}</main>
<footer class="site-footer"><div class="container footer-grid">
<div><a class="brand" href="index.html"><span class="brand-mark">LB</span><span class="brand-copy"><strong>Little Bloom</strong><small>Early Learning Centre</small></span></a><p>A warm, family-friendly approach to early learning.</p></div>
<div><h4>Explore</h4><div class="footer-links"><a href="about.html">About us</a><a href="programs.html">Programs & fees</a><a href="activities.html">Activities</a><a href="gallery.html">Gallery</a></div></div>
<div><h4>Admissions</h4><div class="footer-links"><a href="admission.html">Admission process</a><a href="#" class="open-ai">Chat with Admissions</a><a href="contact.html">Contact</a></div></div>
<div><h4>Contact</h4><p>Surat, Gujarat, India</p><p>Monday–Saturday · 8:00 AM–1:30 PM</p></div>
</div><div class="container footer-bottom"><span>© <span data-year></span> Little Bloom Early Learning Centre</span><span>Website by PaulCodeAI</span></div></footer>
{chat}<div class="toast" id="toast" role="status" aria-live="polite"></div><script src="js/main.js" defer></script></body></html>'''

home=r'''
<section class="hero"><div class="container hero-grid"><div class="hero-copy reveal"><span class="eyebrow">A joyful start to learning</span><h1>Where little minds <span>grow, learn & shine.</span></h1><p>A warm, playful early learning environment where children build confidence, curiosity and a love for learning through everyday experiences.</p><div class="hero-actions"><a class="btn btn-primary" href="admission.html">Explore Admissions →</a><a class="btn btn-ghost" href="programs.html">View Programs</a></div></div><div class="hero-art reveal"><img src="images/hero.svg" alt="Children learning together in a bright preschool environment"><div class="float-card one"><strong>Play-based learning</strong><small>For ages 2–6 years</small></div><div class="float-card two"><strong>Family-first</strong><small>Clear parent communication</small></div></div></div></section>
<section class="section section-green"><div class="container"><div class="section-head center reveal"><span class="eyebrow">Why Little Bloom</span><h2>A happy place to <span>learn and belong.</span></h2><p>Children learn best when the day feels welcoming, active and full of discovery.</p></div><div class="feature-grid"><article class="feature-card reveal"><div class="icon-bubble">♡</div><h3>Warm & Caring</h3><p>Gentle routines and supportive guidance help children feel comfortable and confident.</p></article><article class="feature-card reveal"><div class="icon-bubble">✦</div><h3>Learn Through Play</h3><p>Stories, music, art, movement and discovery turn everyday moments into learning.</p></article><article class="feature-card reveal"><div class="icon-bubble">☀</div><h3>Family Friendly</h3><p>Clear programs, fees and admission information make the parent journey simpler.</p></article><article class="feature-card reveal"><div class="icon-bubble">LB</div><h3>Admissions Support</h3><p>Parents can use the virtual admissions assistant for quick questions any time.</p></article></div></div></section>
<section class="section section-yellow"><div class="container split"><div class="image-panel reveal"><img src="images/classroom.svg" alt="Illustration of a preschool classroom"></div><div class="section-copy reveal"><span class="eyebrow">Our approach</span><h2>Little steps. <span>Big beginnings.</span></h2><p>We combine age-appropriate classroom routines with creative activities, conversation, movement and hands-on discovery.</p><ul class="check-list"><li><span>✓</span> Language and early numeracy through play</li><li><span>✓</span> Creative expression through art and music</li><li><span>✓</span> Group activities that build confidence</li><li><span>✓</span> School-readiness through routines and teamwork</li></ul><a class="text-link" href="about.html">Discover our approach →</a></div></div></section>
<section class="section"><div class="container"><div class="section-head reveal"><span class="eyebrow">Programs & fees</span><h2>Find the right <span>starting point.</span></h2><p>Indicative tuition is shown below to help families understand the structure at a glance.</p></div><div class="program-grid"><article class="program-card reveal"><span class="age">02–03 years</span><h3>Playgroup</h3><p>Gentle routines, social play, stories and sensory exploration.</p><div class="price-line"><strong>₹2,800 / month</strong><span>₹33,600 annual tuition</span></div></article><article class="program-card reveal"><span class="age">03–04 years</span><h3>Nursery</h3><p>Language, early concepts, art, movement and classroom routines.</p><div class="price-line"><strong>₹3,200 / month</strong><span>₹38,400 annual tuition</span></div></article><article class="program-card reveal"><span class="age">04–05 years</span><h3>Junior KG</h3><p>Guided projects, early writing, discovery and group learning.</p><div class="price-line"><strong>₹3,600 / month</strong><span>₹43,200 annual tuition</span></div></article><article class="program-card reveal"><span class="age">05–06 years</span><h3>Senior KG</h3><p>Reading, maths games, teamwork and school-readiness activities.</p><div class="price-line"><strong>₹3,900 / month</strong><span>₹46,800 annual tuition</span></div></article></div><div class="program-link-wrap reveal"><a class="text-link" href="programs.html">See full programs & fee information →</a></div></div></section>
<section class="section section-purple"><div class="container split"><div class="section-copy reveal"><span class="eyebrow">Personalised parent support</span><h2>Have a question about <span>admissions?</span></h2><p>Chat naturally with Little Bloom Admissions about programs, fees, timings, activities and the admission process.</p><button class="btn btn-primary open-ai" type="button">Chat with Admissions</button></div><div class="ai-showcase reveal"><div class="ai-showcase-top"><div class="assistant-avatar">LB</div><div><strong>Little Bloom Admissions</strong><small>Virtual Admissions Assistant · Online</small></div><span class="live-dot">● Online</span></div><div class="assistant-msg">Hi! How can I help you with admissions today?</div><div class="assistant-prompt">“My child is 4 years old. Which program would suit them?”</div></div></div></section>
<section class="section section-orange"><div class="container"><div class="stats-grid"><div class="stat-card reveal"><strong>4</strong><span>age-based learning programs</span></div><div class="stat-card reveal"><strong>6+</strong><span>creative and active learning experiences</span></div><div class="stat-card reveal"><strong>1</strong><span>simple place for parent enquiries</span></div></div></div></section>
<section class="section"><div class="container"><div class="cta-box reveal"><div><h2>Ready to take the next step?</h2><p>Explore the admission process or send your enquiry directly to WhatsApp.</p></div><a class="btn btn-green" href="admission.html">Start an Enquiry →</a></div></div></section>
'''
(root/'index.html').write_text(shell('Home','Little Bloom Early Learning Centre offers a warm, play-based preschool experience for families in Surat.',home),encoding='utf-8')

about=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">About Little Bloom</span><h1>A bright beginning for <span>curious minds.</span></h1><p>Our approach brings together play, conversation, movement, creativity and age-appropriate routines so children can grow with confidence.</p></div></section>
<section class="section"><div class="container split"><div class="image-panel reveal"><img src="images/story.svg" alt="Story and language learning illustration"></div><div class="section-copy reveal"><span class="eyebrow">Our philosophy</span><h2>Childhood deserves <span>room to explore.</span></h2><p>Young children understand the world by doing, talking, moving, creating and asking questions. We design the day around those natural ways of learning.</p><ul class="check-list"><li><span>✓</span> Age-appropriate learning experiences</li><li><span>✓</span> Positive routines and gentle guidance</li><li><span>✓</span> Opportunities to create, move and communicate</li><li><span>✓</span> Strong foundations for the next stage of school</li></ul></div></div></section>
<section class="section section-purple"><div class="container"><div class="section-head center reveal"><span class="eyebrow">Everyday priorities</span><h2>Four things children <span>need to thrive.</span></h2></div><div class="feature-grid"><article class="feature-card reveal"><div class="icon-bubble">01</div><h3>Confidence</h3><p>Encouraging children to try, participate, communicate and make small choices.</p></article><article class="feature-card reveal"><div class="icon-bubble">02</div><h3>Curiosity</h3><p>Hands-on activities that turn everyday questions into moments of discovery.</p></article><article class="feature-card reveal"><div class="icon-bubble">03</div><h3>Connection</h3><p>Stories, group play and classroom routines that practise communication and cooperation.</p></article><article class="feature-card reveal"><div class="icon-bubble">04</div><h3>Readiness</h3><p>Early literacy, numeracy and classroom habits that support the next learning stage.</p></article></div></div></section>
<section class="section section-green"><div class="container"><div class="cta-box reveal"><div><h2>Want to compare programs?</h2><p>See age groups, learning focus and indicative fees together.</p></div><a class="btn btn-primary" href="programs.html">View Programs & Fees</a></div></div></section>
'''
(root/'about.html').write_text(shell('About Us','Learn about Little Bloom Early Learning Centre and its family-friendly, play-based approach to early learning.',about),encoding='utf-8')

programs=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">Programs & fees</span><h1>Simple choices for <span>every early stage.</span></h1><p>Age-based programs with indicative tuition, learning focus and additional costs families may want to plan for.</p></div></section>
<section class="section"><div class="container program-list">
<article class="program-detail reveal"><div class="program-badge">01</div><div><span class="eyebrow">02–03 years</span><h2>Playgroup</h2><p>Gentle routines, social play, sensory exploration, stories and music help children become comfortable in a group setting.</p><div class="tag-row"><span class="tag">Sensory Play</span><span class="tag">Story Time</span><span class="tag">Music</span><span class="tag">Free Play</span></div><div class="fee-box"><h4>Indicative tuition</h4><div class="fee-grid"><div class="fee-item"><strong>₹2,800</strong><span>per month</span></div><div class="fee-item"><strong>₹33,600</strong><span>annual tuition</span></div><div class="fee-item"><strong>₹5,000</strong><span>one-time admission</span></div></div></div></div></article>
<article class="program-detail reveal"><div class="program-badge">02</div><div><span class="eyebrow">03–04 years</span><h2>Nursery</h2><p>Language development, early number concepts, art, movement and classroom routines help children build confidence and independence.</p><div class="tag-row"><span class="tag">Phonics</span><span class="tag">Art</span><span class="tag">Rhymes</span><span class="tag">Discovery</span></div><div class="fee-box"><h4>Indicative tuition</h4><div class="fee-grid"><div class="fee-item"><strong>₹3,200</strong><span>per month</span></div><div class="fee-item"><strong>₹38,400</strong><span>annual tuition</span></div><div class="fee-item"><strong>₹5,000</strong><span>one-time admission</span></div></div></div></div></article>
<article class="program-detail reveal"><div class="program-badge">03</div><div><span class="eyebrow">04–05 years</span><h2>Junior KG</h2><p>Guided projects, early writing, creative work, discovery and group learning encourage communication and problem solving.</p><div class="tag-row"><span class="tag">Early Writing</span><span class="tag">STEM Play</span><span class="tag">Projects</span><span class="tag">Teamwork</span></div><div class="fee-box"><h4>Indicative tuition</h4><div class="fee-grid"><div class="fee-item"><strong>₹3,600</strong><span>per month</span></div><div class="fee-item"><strong>₹43,200</strong><span>annual tuition</span></div><div class="fee-item"><strong>₹5,000</strong><span>one-time admission</span></div></div></div></div></article>
<article class="program-detail reveal"><div class="program-badge">04</div><div><span class="eyebrow">05–06 years</span><h2>Senior KG</h2><p>Reading, maths games, discovery projects, teamwork and school-readiness routines prepare children for the next stage of formal learning.</p><div class="tag-row"><span class="tag">Reading</span><span class="tag">Math Games</span><span class="tag">Experiments</span><span class="tag">School Ready</span></div><div class="fee-box"><h4>Indicative tuition</h4><div class="fee-grid"><div class="fee-item"><strong>₹3,900</strong><span>per month</span></div><div class="fee-item"><strong>₹46,800</strong><span>annual tuition</span></div><div class="fee-item"><strong>₹5,000</strong><span>one-time admission</span></div></div></div></div></article>
</div></section>
<section class="section section-yellow"><div class="container"><div class="section-head reveal"><span class="eyebrow">Additional costs</span><h2>Plan for the <span>whole year.</span></h2><p>These planning figures make the fee structure easier to understand; final charges should be confirmed with admissions.</p></div><div class="detail-grid"><article class="content-card reveal"><div class="icon-bubble">₹</div><h3>Activity & learning materials</h3><p><strong>₹4,500 / year</strong></p><p>For classroom resources and activity materials.</p></article><article class="content-card reveal"><div class="icon-bubble">▣</div><h3>Books & uniform</h3><p><strong>Approx. ₹5,000 / year</strong></p><p>Indicative cost for books and basic uniform requirements.</p></article><article class="content-card reveal"><div class="icon-bubble">↗</div><h3>Transport</h3><p><strong>₹1,800–₹2,500 / month</strong></p><p>Depending on route availability.</p></article><article class="content-card reveal"><div class="icon-bubble">?</div><h3>Need the full breakdown?</h3><p>Chat with Little Bloom Admissions or send an enquiry on WhatsApp.</p></article></div></div></section>
<section class="section section-purple"><div class="container cta-box reveal"><div><h2>Not sure which program fits?</h2><p>Start a conversation with the virtual admissions assistant.</p></div><button class="btn btn-primary open-ai" type="button">Chat with Admissions</button></div></section>
'''
(root/'programs.html').write_text(shell('Programs & Fees','Explore Little Bloom preschool programs, learning focus and indicative tuition fees for Playgroup, Nursery, Junior KG and Senior KG.',programs),encoding='utf-8')

activities=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">Activities</span><h1>Every day brings a new <span>way to explore.</span></h1><p>Creative, active and social experiences help children learn through doing.</p></div></section>
<section class="section"><div class="container activity-grid"><article class="media-card reveal"><img src="images/art.svg" alt="Art and craft activity"><div class="body"><h3>Art & Craft</h3><p>Colour, texture, cutting, sticking and making encourage expression and fine-motor practice.</p></div></article><article class="media-card reveal"><img src="images/story.svg" alt="Storytelling activity"><div class="body"><h3>Storytelling</h3><p>Stories and conversations support vocabulary, listening, imagination and confidence.</p></div></article><article class="media-card reveal"><img src="images/music.svg" alt="Music and movement activity"><div class="body"><h3>Music & Movement</h3><p>Rhythm, action songs and movement games turn learning into an active experience.</p></div></article><article class="media-card reveal"><img src="images/outdoor.svg" alt="Outdoor play activity"><div class="body"><h3>Outdoor Play</h3><p>Movement and group games support coordination, confidence and social interaction.</p></div></article><article class="media-card reveal"><img src="images/classroom.svg" alt="Discovery activity"><div class="body"><h3>Little Explorers</h3><p>Simple observations and discovery activities turn everyday questions into playful learning.</p></div></article><article class="media-card reveal"><img src="images/hero.svg" alt="Group learning activity"><div class="body"><h3>Group Projects</h3><p>Collaborative activities help children practise communication, sharing and teamwork.</p></div></article></div></section>
<section class="section section-green"><div class="container"><div class="section-head center reveal"><span class="eyebrow">A balanced day</span><h2>Learning, movement and <span>quiet moments.</span></h2><p>A typical day can include welcoming routines, focused learning, active play, creative time and stories.</p></div><div class="detail-grid"><article class="content-card reveal"><h3>Morning welcome</h3><p>Greetings, circle time and simple routines help children settle in comfortably.</p></article><article class="content-card reveal"><h3>Focused learning</h3><p>Age-appropriate language, numeracy, art or discovery activities led in small groups.</p></article><article class="content-card reveal"><h3>Active play</h3><p>Outdoor time and movement add energy and balance to the day.</p></article><article class="content-card reveal"><h3>Stories & reflection</h3><p>Stories, conversation and quiet activities help children close the day calmly.</p></article></div></div></section>
'''
(root/'activities.html').write_text(shell('Activities','Explore Little Bloom preschool activities including art, storytelling, music, outdoor play and group projects.',activities),encoding='utf-8')

gallery=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">Gallery</span><h1>A glimpse into a <span>playful learning day.</span></h1><p>Bright scenes from classroom learning, creative work, stories, music and outdoor activity.</p></div></section>
<section class="section"><div class="container detail-grid"><article class="content-card reveal"><img src="images/hero.svg" alt="Children learning together"><h3>Welcome to Little Bloom</h3><p>A bright, welcoming start to the learning day.</p></article><article class="content-card reveal"><img src="images/classroom.svg" alt="Preschool classroom"><h3>Classroom Moments</h3><p>Learning spaces designed to encourage participation and curiosity.</p></article><article class="content-card reveal"><img src="images/art.svg" alt="Art activity"><h3>Creative Corner</h3><p>Art and making activities encourage self-expression.</p></article><article class="content-card reveal"><img src="images/outdoor.svg" alt="Outdoor play"><h3>Active Play</h3><p>Fresh air, movement and group play.</p></article><article class="content-card reveal"><img src="images/music-movement.png" alt="Music and movement"><h3>Music & Movement</h3><p>Rhythm, action songs and movement games.</p></article><article class="content-card reveal"><img src="images/story.svg" alt="Story time"><h3>Story Time</h3><p>Stories that build language and imagination.</p></article></div></section>
<section class="section section-yellow"><div class="container cta-box reveal"><div><h2>Have questions about the school?</h2><p>Chat with Little Bloom Admissions for programs, fees and admission information.</p></div><button class="btn btn-primary open-ai" type="button">Chat with Admissions</button></div></section>
'''
(root/'gallery.html').write_text(shell('Gallery','See a selection of Little Bloom classroom, creative, story, music and outdoor learning scenes.',gallery),encoding='utf-8')

admission=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">Admissions</span><h1>A simple start for your <span>family.</span></h1><p>Choose a program, send an enquiry and let the admissions team guide you through the next steps.</p></div></section>
<section class="section"><div class="container detail-grid"><article class="content-card reveal"><div class="icon-bubble">01</div><h3>Choose a program</h3><p>Review age groups, learning focus and indicative tuition.</p></article><article class="content-card reveal"><div class="icon-bubble">02</div><h3>Send an enquiry</h3><p>Share your child's age, preferred program and your question.</p></article><article class="content-card reveal"><div class="icon-bubble">03</div><h3>Speak with admissions</h3><p>Confirm availability, final fees and any current requirements.</p></article><article class="content-card reveal"><div class="icon-bubble">04</div><h3>Plan the next step</h3><p>Arrange a visit and complete the school's enrolment process.</p></article></div></section>
<section class="section section-orange"><div class="container form-wrap"><div class="form-card reveal"><div class="section-head"><span class="eyebrow">Admission enquiry</span><h2>Tell us a little about your <span>child.</span></h2><p>Complete the form and we'll prepare the enquiry for WhatsApp.</p></div><form data-whatsapp-form data-type="admission"><div class="form-grid"><div class="field"><label for="ad-name">Parent name</label><input id="ad-name" name="name" required placeholder="Your name"></div><div class="field"><label for="ad-phone">Phone</label><input id="ad-phone" name="phone" required inputmode="tel" placeholder="10-digit mobile number"></div><div class="field"><label for="ad-age">Child age</label><select id="ad-age" name="age" required><option value="">Select</option><option>2–3 years</option><option>3–4 years</option><option>4–5 years</option><option>5–6 years</option></select></div><div class="field"><label for="ad-program">Preferred program</label><select id="ad-program" name="program" required><option value="">Select</option><option>Playgroup</option><option>Nursery</option><option>Junior KG</option><option>Senior KG</option></select></div><div class="field full"><label for="ad-message">Your question</label><textarea id="ad-message" name="message" placeholder="Tell us what you would like to know"></textarea></div></div><button class="btn btn-green" type="submit">Send Enquiry on WhatsApp ↗</button><p class="form-note">You’ll be taken to a WhatsApp handoff page. On mobile, it will open WhatsApp with the enquiry details ready to send.</p></form></div><div class="contact-card reveal"><span class="eyebrow">Need help first?</span><h2>Ask the <span>virtual admissions assistant.</span></h2><p>Ask naturally about programs, indicative fees, activities or the admission process before sending your enquiry.</p><button class="btn btn-primary open-ai" type="button">Chat with Admissions</button><div class="contact-list"><div class="contact-item"><small>Admission fee</small><strong>₹5,000 one-time</strong></div><div class="contact-item"><small>Activity & learning materials</small><strong>₹4,500 / year</strong></div><div class="contact-item"><small>Transport</small><strong>₹1,800–₹2,500 / month</strong></div></div></div></div></section>
'''
(root/'admission.html').write_text(shell('Admissions','Learn how the Little Bloom admission process works and send a structured enquiry to WhatsApp.',admission),encoding='utf-8')

contact=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">Contact</span><h1>Let's make the next step <span>simple.</span></h1><p>Send a question to the admissions team or use the virtual assistant for quick information.</p></div></section>
<section class="section"><div class="container form-wrap"><div class="form-card reveal"><div class="section-head"><span class="eyebrow">General enquiry</span><h2>How can we <span>help?</span></h2><p>Your message will be prepared for WhatsApp so the admissions team can respond directly.</p></div><form data-whatsapp-form data-type="contact"><div class="form-grid"><div class="field"><label for="ct-name">Name</label><input id="ct-name" name="name" required placeholder="Your name"></div><div class="field"><label for="ct-phone">Phone</label><input id="ct-phone" name="phone" required inputmode="tel" placeholder="10-digit mobile number"></div><div class="field"><label for="ct-email">Email</label><input id="ct-email" name="email" type="email" placeholder="you@example.com"></div><div class="field"><label for="ct-topic">Topic</label><select id="ct-topic" name="topic"><option>Admission</option><option>Programs</option><option>Fees</option><option>Activities</option><option>General enquiry</option></select></div><div class="field full"><label for="ct-message">Message</label><textarea id="ct-message" name="message" required placeholder="How can we help?"></textarea></div></div><button class="btn btn-green" type="submit">Send Enquiry on WhatsApp ↗</button><p class="form-note">On mobile, WhatsApp opens with your message ready. On desktop, WhatsApp Web may open.</p></form></div><div class="contact-card reveal"><span class="eyebrow">Little Bloom</span><h2>Find us in <span>Surat.</span></h2><p>Surat, Gujarat, India</p><div class="contact-list"><div class="contact-item"><small>School hours</small><strong>Monday–Saturday · 8:00 AM–1:30 PM</strong></div><div class="contact-item"><small>Admissions support</small><strong>Chat with the virtual assistant</strong></div><div class="contact-item"><small>Location</small><strong>Surat, Gujarat</strong></div></div><div class="map-card"><img src="images/map.svg" alt="Illustrated map of Surat, Gujarat"><div class="map-copy"><strong>Surat, Gujarat</strong><p>Map shown for the school location area.</p><a class="btn btn-ghost" href="https://www.google.com/maps/search/Surat%2C+Gujarat" target="_blank" rel="noopener">Open Surat in Google Maps</a></div></div></div></div></section>
'''
(root/'contact.html').write_text(shell('Contact','Contact Little Bloom Early Learning Centre for admissions, programs and general enquiries in Surat.',contact),encoding='utf-8')

whatsapp=r'''
<section class="page-hero"><div class="container"><span class="eyebrow">WhatsApp enquiry</span><h1>Opening <span>WhatsApp…</span></h1><p>Your enquiry details are being prepared. Please wait a moment.</p></div></section>
<section class="section"><div class="container redirect-card"><div class="whatsapp-icon">WA</div><h2>Continue to WhatsApp</h2><p id="wa-status">Preparing your enquiry message…</p><div class="redirect-spinner" aria-hidden="true"></div><a id="wa-fallback" class="btn btn-green" href="#" hidden>Open WhatsApp manually</a><p class="form-note">Your message will not be sent until you press <strong>Send</strong> in WhatsApp.</p></div></section>
'''
(root/'whatsapp-redirect.html').write_text(shell('WhatsApp Enquiry','Continue to WhatsApp with your Little Bloom enquiry details.',whatsapp,no_chat=True),encoding='utf-8')

# generic 404
error="<section class='page-hero'><div class='container'><span class='eyebrow'>404</span><h1>That page <span>isn't here.</span></h1><p>Let's get you back to the Little Bloom home page.</p><div class='hero-actions page-actions-spaced'><a class='btn btn-primary' href='index.html'>Back to Home</a></div></div></section>"
(root/'404.html').write_text(shell('Page Not Found','The requested page could not be found.',error,no_chat=True),encoding='utf-8')

print('built pages')
